# Generated by Django 4.2.2 on 2023-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliindie', '0002_utilisateur_studio_nomstudio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jeu',
            constraint=models.CheckConstraint(check=models.Q(('prixJeu__range', (0, 2000))), name='appliindie_jeu_prixJeu_range'),
        ),
    ]
